models/modelProject.py
from database.connectDB import get_connection_SQL_SERVER


class modelProject:
    @staticmethod
    def get_dataBank():
        connection = get_connection_SQL_SERVER()
        with connection.cursor() as cursor:
            try:
                query = "SELECT IDBCO, DESCRIPCION FROM BANCOS"
                cursor.execute(query)
                result = cursor.fetchall()
                return result

            except Exception as e:
                print(f"Error en la consulta {str(e)}")
                return []

    # Insert
    @staticmethod
    def insert_bank(description):
        connection = get_connection_SQL_SERVER()
        mycursor = connection.cursor()
        SQLINSERT = "INSERT INTO Bancos (DESCRIPCION) VALUES(?)"
        try:
            mycursor.execute(SQLINSERT, description)
        except:
            connection.rollback()
        else:
            connection.commit()
        finally:
            connection.close()
            return True

    @staticmethod
    def update_bank(idbank, description):
        connection = get_connection_SQL_SERVER()
        mycursor = connection.cursor()
        SQLUPDATE = "UPDATE Bancos SET DESCRIPCION=? WHERE  IDBCO=?"
        try:
            mycursor.execute(SQLUPDATE, description, idbank)
        except:
            connection.rollback()
        else:
            connection.commit()
        finally:
            connection.close()
            return True

    @staticmethod
    def delete_bank(idbank):
        connection = get_connection_SQL_SERVER()
        mycursor = connection.cursor()
        SQLDELETE = "DELETE FROM Bancos WHERE IDBCO=?"
        try:
            mycursor.execute(SQLDELETE, idbank)
        except:
            connection.rollback()
        else:
            connection.commit()
        finally:
            connection.close()
            return True

views/viewProject.py
from flask import Blueprint, render_template, request
from models.modelProject import modelProject

main = Blueprint("datatable_bp", __name__)


@main.route('/allBanks')
def getBanks():
    banks = modelProject.get_dataBank()
    return render_template('/mantenimiento.html', banks=banks)


@main.route('/insert', methods=['POST', 'GET'])
def insertBank():
    if request.method == "POST":
        data = request.get_json()
        descripcion = data.get('bank', None)
        modelProject.insert_bank(descripcion)
    return "OK"


@main.route('/update', methods=['POST', 'GET'])
def updateBank():
    if request.method == "POST":
        data = request.get_json()
        idbco = data.get('idbco', None)
        descripcion = data.get('bank', None)
        modelProject.update_bank(idbco, descripcion)
    return "OK"


@main.route('/delete', methods=['POST', 'GET'])
def deleteBank():
    if request.method == "POST":
        data = request.get_json()
        idbco = data.get('idbco', None)
        modelProject.delete_bank(idbco)
    return "OK"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} {% endblock %}</title>

        <!---Agrega un favicon , es agregar una pequeña imagen localizada en el tab de un navegador --->
     <link  rel="icon" type="image/x-icon" href="https://cdn.jsdelivr.net/npm/twemoji@11.3.0/2/svg/1f47d.svg" />

    <!-- Enlace a Bootstrap 5.0.2 CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>

    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css">

   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
        <!-- DataTables CSS para button-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">

     <!-- DataTables ejemplo 7-->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchbuilder/1.6.0/css/searchBuilder.dataTables.min.css">
 <!-- DataTables ejemplo 7-->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/datetime/1.5.1/css/dataTables.dateTime.min.css">


    <!-- DataTables JavaScript -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>


      <!-- DataTables JavaScript rowgroup -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/rowgroup/1.4.1/js/dataTables.rowGroup.min.js"></script>

         <!---DataTables JavaScript  button Ejemplo 5 -->
    <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js></script>
        <!---DataTables JavaScript Print button Ejemplo 5 -->
    <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js></script>

    <!---DataTables JavaScript Boton colVis, opcion para columnas visible a travez de un button Ejemplo 5 -->
    <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js></script>


     <!---DataTables : libreria JavaScript permite crear, leer y editar archivos zip Ejemplo 6 -->
  <script type="text/javascript" charset="utf8" src=https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js></script>

<!---DataTables : libreria JavaScript permite crer archivos PDF Ejemplo 6 -->
  <script type="text/javascript" charset="utf8" src=https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js></script>

    <!---DataTables : libreria JavaScript para tipo de letras  exportacion de PDF Ejemplo 6 -->
  <script type="text/javascript" charset="utf8" src=https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js></script>

    <!---DataTables : libreria JavaScript para boton HTML5 de exportación Ejemplo 6 -->
  <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js></script>

        <!---DataTables : libreria JavaScript para boton Construcción de COnsulta Ejemplo 7 -->
  <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/searchbuilder/1.6.0/js/dataTables.searchBuilder.min.js></script>
    <!---DataTables : libreria JavaScript para control de fecha de COnsulta Ejemplo 7 -->
  <script type="text/javascript" charset="utf8" src=https://cdn.datatables.net/datetime/1.5.1/js/dataTables.dateTime.min.js></script>

 <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.5"></script>

</head>

<body>

<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Mantenimiento</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('datatable_bp.getBanks') }}">Mantenimiento Bancos</a>
         </li>

      </ul>

    </div>
  </div>
</nav>


</header>

<div class="container py-3">
    {% block body %}

    {% endblock %}
</div>

<!-- Bootstrap 5.0.2 incluye la biblioteca Popper, por lo que no necesitas cargarla por separado. -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

</body>
</html>

templates/index.html
{% extends './base.html' %}

{% block title  %} Index {% endblock %}

{%  block body %}

{% endblock %}

templates/mantenimiento.html
{% extends './base.html' %}
{% block title %}Mantenimiento {% endblock %}
{% block body %}

<!-- Contenedor principal -->
    <!-- Div centrado con color llamativo y título -->
    <div class="text-center bg-primary text-white  ">
            <!-- Reducir el tamaño del título al 50% -->
            <h1 class="display-5">Mantenimiento Bancos</h1>
    </div>

<div class="row">
    <div class="col-md-3 mb-3">
      <label for="txtBank" class="form-label" >Bank Name:</label>
      <input type="text" class="form-control" id="txtBank" name="txtBank">
    </div>
</div>

<div class="row">
    <div class="col-md-3 mb-3">
      <button id="addRow" class="btn btn-primary mr-2">Add</button>
      <button id="editRow" class="btn btn-primary mr-2">Edit</button>
      <button id="delRow" class="btn btn-primary mr-2">Remove</button>
    </div>
</div>

 <div class="row">
     <div class="col-sm-12">
         <table id="table_id" class="display" style="width:100%">
             <thead>
             <tr>
                 <th>Code Bank</th>
                  <th>Bank Name</th>
             </tr>
             <tbody>
                {% for row in banks %}
                <tr>
                     <td>{{ row.IDBCO }}</td>
                    <td>{{ row.DESCRIPCION }}</td>
                </tr>
                {%  endfor %}
             </tbody>
             </thead>
         </table>
            </div>
     </div>

<script src="{{url_for( 'static', filename='js/functionCRUD.js') }}">  </script>

<script>

     $(document).ready(function () {
       var table= $('#table_id').DataTable({
            ordering:false
        } );
        var bank= $('#txtBank');
        var databank;
        var Idbco;

        $('#table_id tbody').on('click','tr',function(){
          if ($(this).hasClass('selected')){
              $(this).removeClass('selected');
          }
          else{
             table.$('tr.selected').removeClass('selected');
             $(this).addClass('selected');
             databank = table.row(this).data();
             bank.val(databank[1]);
             Idbco=databank[0];
          }
        });

        $('#addRow').on('click',function (e){
            e.preventDefault();
            var newBank = bank.val()
            //Verificar newBank tiene datos
            if (newBank.length >0){
                CRUD_promesa("", newBank, '/insert').then(function (response){
                    //Operaciones después del éxito
                    Swal.fire({
                        title: "Mantenimiento",
                        text: "Operación Realizada",
                        icon: "succes",
                        willClose :  function () {
                                        window.location.href = '/allBanks';
                                   }
                    });
                })
                .catch(function (error){
                    //manejo de errores
                    Swal.fire({
                        icon: "error",
                        title:"Mantenimiento",
                        text: "Error al procesar el dato."
                    });
                });
                //llamar funcion CRUD
                 ClearText();
            }else {
                console.error('La longitud de NewBank es cero o menor.');
            }
        });

        $('#editRow').on('click',function (){
           var newBank = bank.val()
            if (newBank.length >0){
                var selectedRow = table.row('.selected');

                CRUD_promesa(Idbco, newBank, '/update').then(function (response){
                    //Operaciones después del éxito
                    Swal.fire({
                        title: "Mantenimiento",
                        text: "Operación Realizada",
                        icon: "succes",
                        willClose :  function () {
                                        window.location.href = '/allBanks';
                                   }
                    });
                })
                .catch(function (error){
                    //manejo de errores
                    Swal.fire({
                        icon: "error",
                        title:"Mantenimiento",
                        text: "Error al procesar el dato."
                    });
                });

            }else {
                console.error('La longitud de NewBank es cero o menor.');
            }

        });

        $('#delRow').on('click',function (){
            var newBank = bank.val()
             if (newBank.length >0){
                Swal.fire({
                    title: "Desea remover el registro actual?",
                      showDenyButton: false,
                      showCancelButton: true
                }).then((result) => {
                    if(result.isConfirmed){

                        CRUD_promesa(Idbco, newBank, '/delete').then(function (response){
                        //Operaciones después del éxito
                        Swal.fire({
                            title: "Mantenimiento",
                            text: "Operación Realizada",
                            icon: "succes",
                            willClose :  function () { window.location.href = '/allBanks'; }
                        });
                    })
                    .catch(function (error){
                        //manejo de errores
                        Swal.fire({
                            icon: "error",
                            title:"Mantenimiento",
                            text: "Error al procesar el dato."
                        });
                    });
                       ClearText();
                    }
                });
             }
             else {
                console.error('La longitud de NewBank es cero o menor.');
             }
        });

        function ClearText(){
             bank.val("")
        }

        function CRUD_promesa(idbco, bank, url) {
            return new Promise(function (resolve, reject){
               var formData = {
                idbco: idbco,
                bank:bank
            };
              //Realizar solicitud AJAX  usando JQuey
           $.ajax({
                    //configurar solicitud POST
                    type:'POST',
                    //Especificar la URL
                    url: url,
                    contentType: 'application/json;charset=UTF-8',
                    //CONVERTIR obj a JSON
                    data: JSON.stringify(formData),

                    success: function (response) {
                       //resuelve la promesa con la respuesta
                       resolve(response);
                    },
                    //Funcion ejecuta en caso de problema
                    error: function (error){
                        //rechaza la promesa con el error
                        reject(error);
                     },
                    complete: function () {
                        //Agregar codigo que desees ejecutar despues de la solicitud
                    }
                });
              });
            }
    });

</script>

{% endblock %}